### ISSUE TITLE
Add more information about the "Defining a language" section

### ISSUE THREAD

**Issue by emanuelps2708** [LuteOrg/lute-manual#1]
Hi Jz, I think some things could be added/edited to that section of the manual. I would suggest to add:

> When creating a new Language, you can use one of the existing languages as a template by going to the "Languages" section of the settings and selecting the "Load predefined language and sample stories" drop-down at the bottom of the form, clicking the language or using the searching bar to find what you're interested. Sensible defaults are set.

![image](https://github.com/LuteOrg/lute-manual/assets/147004033/7625df6e-fe00-475c-9fa9-a0e88cfb2e78)

> If the language you're interested in is not there you can check a [spreadsheet](https://docs.google.com/spreadsheets/d/1iBSwsKI-57HpjnNP8holmk_HDmjh16i5V_G8HJ-oNHY/edit#gid=1003964927) created by the community with a lot of languages and dictionaries.

**Comment by emanuelps2708** [comment]
I plan adding/expanding more info in the manual based on a [draft](https://docs.google.com/document/d/1J1vWkZlKCxiTpycY60DE84eMl-VKEYcAyCynSWgpAhQ/edit#heading=h.swplum1c1imu) that I made before so people learning not so common languages or interested in knowing more about adding languages to lute

**Comment by jzohrab** [comment]
Good enough for now, thank you @emanuelps2708 !
